using System.Text;
using System.Text.Json;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Goose.Tools.SpriteBundle;

/// <summary>Renders one bundle as an HTML fragment for the Apps Script project: the atlas as a
/// base64 data URI plus its rect index. Base64 costs 33% over the raw PNG; HtmlService gzips
/// on the way out, so the wire cost is close to the PNG size.</summary>
public static class BundleWriter
{
    public static string Render(string name, Image<Rgba32> atlas,
                               IReadOnlyDictionary<string, SpriteRect> rects)
    {
        using var ms = new MemoryStream();
        atlas.SaveAsPng(ms);
        var b64 = Convert.ToBase64String(ms.ToArray());

        var sb = new StringBuilder();
        sb.Append("<script>\n");
        sb.Append("// Generated by tools/SpriteBundle. Do not edit by hand.\n");
        sb.Append("var GOOSE_SPRITES = GOOSE_SPRITES || {};\n");
        sb.Append($"GOOSE_SPRITES[{Js(name)}] = {{\n");
        sb.Append($"  \"width\": {atlas.Width},\n");
        sb.Append($"  \"height\": {atlas.Height},\n");
        sb.Append($"  \"png\": \"data:image/png;base64,{b64}\",\n");
        sb.Append("  \"rects\": {\n");

        // Ordinal so the output is byte-stable across machines and runs: these fragments are
        // committed, and a culture- or hash-ordered index would churn the diff every build.
        var i = 0;
        foreach (var (key, r) in rects.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            var comma = ++i < rects.Count ? "," : "";
            sb.Append($"    {Js(key)}: [{r.X},{r.Y},{r.W},{r.H}]{comma}\n");
        }

        sb.Append("  }\n");
        sb.Append("};\n");
        sb.Append("</script>\n");
        return sb.ToString();
    }

    /// <summary>Quotes a string as a JS/JSON literal. Keys are derived from asset directory
    /// names, so they are not wholly under this tool's control; interpolated raw, a quote or
    /// backslash would emit broken JS that nothing in the pipeline parses, and the failure would
    /// only surface in the browser. Escaping rather than rejecting, because a bundle must not
    /// fail to build over one oddly-named asset.
    ///
    /// The default (HTML-strict) encoder is deliberate: this literal sits inside a &lt;script&gt;
    /// element, where "&lt;/script&gt;" terminates the tag no matter how the JS quotes it, so
    /// escaping only the JSON-unsafe characters would not be enough.</summary>
    private static string Js(string value) => JsonSerializer.Serialize(value);
}
