// Generated by tools/SchemaGen. Do not edit by hand.
var GOOSE_SCHEMA = {
  "sheets": [
    {
      "sheet": "Items",
      "table": "item_templates",
      "columns": [
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "item_usetype",
          "kind": "Enum",
          "sql": "SMALLINT",
          "required": true,
          "pk": false,
          "enumNames": [
            "NoUse",
            "OneTime",
            "Armor",
            "Weapon",
            "Scroll",
            "HairDye",
            "Letter",
            "Money",
            "Recipe"
          ]
        },
        {
          "name": "item_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "item_description",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "player_hp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "player_mp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "player_sp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_ac",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_str",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_sta",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_dex",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_int",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_fire",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_water",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_spirit",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_air",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_earth",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "weapon_damage",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "weapon_delay",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "10",
          "required": false,
          "pk": false
        },
        {
          "name": "item_slot",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "20",
          "required": false,
          "pk": false,
          "enumNames": [
            "Helmet",
            "Shield",
            "OneHanded",
            "TwoHanded",
            "Ring",
            "Necklace",
            "Pauldrons",
            "Cloak",
            "Belt",
            "Gloves",
            "Chest",
            "Pants",
            "Shoes",
            "Mount",
            "Misc"
          ]
        },
        {
          "name": "item_type",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "None",
            "Plate",
            "Leather",
            "Cloth",
            "Mail",
            "OneHandedSword",
            "TwoHandedSword",
            "OneHandedBlunt",
            "TwoHandedBlunt",
            "OneHandedPierce",
            "TwoHandedPierce",
            "Fist"
          ]
        },
        {
          "name": "item_value",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "lore",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "bindonpickup",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "bindonequip",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "event",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_tile",
          "kind": "Int",
          "sql": "INT",
          "required": true,
          "pk": false
        },
        {
          "name": "graphic_file",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_equip",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_r",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_g",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_b",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "graphic_a",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "class_restrictions",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stack_size",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "body_state",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "3",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_effect_id",
          "kind": "Id",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "ref": "Spell Effects"
        },
        {
          "name": "spell_effect_chance",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "100",
          "required": false,
          "pk": false
        },
        {
          "name": "learn_spell_id",
          "kind": "Id",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "ref": "Spells"
        },
        {
          "name": "credits_value",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [
        {
          "kind": "Graphic",
          "columns": [
            "graphic_tile",
            "graphic_file"
          ]
        },
        {
          "kind": "Rgba",
          "columns": [
            "graphic_r",
            "graphic_g",
            "graphic_b",
            "graphic_a"
          ]
        },
        {
          "kind": "Bitmask",
          "columns": [
            "class_restrictions"
          ],
          "source": "Classes"
        }
      ],
      "indexes": []
    },
    {
      "sheet": "NPCs",
      "table": "npc_templates",
      "columns": [
        {
          "name": "npc_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "npc_type",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "2",
          "required": false,
          "pk": false,
          "enumNames": [
            "Monster",
            "Vendor",
            "Banker",
            "Quest"
          ]
        },
        {
          "name": "npc_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "npc_title",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_surname",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "respawn_time",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_facing",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "3",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_level",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "aggro_range",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "attack_range",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "attack_speed",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "2",
          "required": false,
          "pk": false
        },
        {
          "name": "move_speed",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "2",
          "required": false,
          "pk": false
        },
        {
          "name": "stationary",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "stunnable",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "rootable",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "slowable",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "invincible",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_hp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_mp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_sp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "class_id",
          "kind": "Id",
          "sql": "SMALLINT",
          "default": "1",
          "required": false,
          "pk": false,
          "ref": "Classes"
        },
        {
          "name": "stat_ac",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_str",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_sta",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_dex",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_int",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_fire",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_water",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_spirit",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_air",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_earth",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_state",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "body_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "body_r",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_g",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_b",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_a",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "face_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_r",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_g",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_b",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_a",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "equipped_items",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u00270,*,0,*,0,*,0,*,0,*,0,*\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "weapon_damage",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "armor_pierce",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "npc_alliance",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "stuck_behaviour",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "DoNothing",
            "TeleportToAggro",
            "TeleportAggro"
          ]
        },
        {
          "name": "stuck_timeout",
          "kind": "Int",
          "sql": "INT",
          "default": "20",
          "required": false,
          "pk": false
        },
        {
          "name": "credit_dealer",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "quest_ids",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027Scripts/NPC/BaseNPC.csx\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [
        {
          "kind": "Rgba",
          "columns": [
            "body_r",
            "body_g",
            "body_b",
            "body_a"
          ]
        },
        {
          "kind": "Rgba",
          "columns": [
            "hair_r",
            "hair_g",
            "hair_b",
            "hair_a"
          ]
        },
        {
          "kind": "EquipSlots",
          "columns": [
            "equipped_items"
          ]
        },
        {
          "kind": "IdList",
          "columns": [
            "quest_ids"
          ],
          "source": "Quests"
        }
      ],
      "indexes": []
    },
    {
      "sheet": "NPC Spawns",
      "table": "npc_spawns",
      "columns": [
        {
          "name": "npc_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "NPCs"
        },
        {
          "name": "map_id",
          "kind": "Id",
          "sql": "SMALLINT",
          "required": true,
          "pk": false,
          "ref": "Maps"
        },
        {
          "name": "map_x",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "map_y",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "NPC Drops",
      "table": "npc_drops",
      "columns": [
        {
          "name": "npc_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "NPCs"
        },
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Items"
        },
        {
          "name": "stack",
          "kind": "Int",
          "sql": "INT",
          "required": true,
          "pk": false
        },
        {
          "name": "droprate",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "required": true,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "NPC Vendor Items",
      "table": "npc_vendor_items",
      "columns": [
        {
          "name": "npc_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "NPCs"
        },
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Items"
        },
        {
          "name": "stack",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "stats_visible",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "slot",
          "kind": "Int",
          "sql": "INT",
          "required": true,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": [
        "npc_template_id"
      ]
    },
    {
      "sheet": "Quests",
      "table": "quests",
      "columns": [
        {
          "name": "id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "description",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "pass_text",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "fail_text",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "class_restrictions",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "repeatable",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "show_progress",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "only_one_player_can_complete",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "prerequisite_quests",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Quest Reqs",
      "table": "quest_requirements",
      "columns": [
        {
          "name": "id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "quest_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Quests"
        },
        {
          "name": "requirement_type",
          "kind": "Enum",
          "sql": "INT",
          "required": true,
          "pk": false,
          "enumNames": [
            "Gold",
            "Item",
            "Kill",
            "TalkToNPC",
            "ExperienceBanked",
            "ExperienceSold",
            "NothingEquipped"
          ]
        },
        {
          "name": "requirement_value",
          "kind": "Int",
          "sql": "BIGINT",
          "required": true,
          "pk": false
        },
        {
          "name": "requirement_value2",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "keep_requirement",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Quest Rewards",
      "table": "quest_rewards",
      "columns": [
        {
          "name": "id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "quest_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Quests"
        },
        {
          "name": "reward_type",
          "kind": "Enum",
          "sql": "INT",
          "required": true,
          "pk": false,
          "enumNames": [
            "Gold",
            "Item",
            "Title",
            "Surname",
            "Teleport",
            "Experience",
            "FaceGraphic",
            "BodyGraphic",
            "HairGraphic",
            "HairColour",
            "BodyColour",
            "ClassChange",
            "HP",
            "MP",
            "AC",
            "Stamina",
            "Strength",
            "Dexterity",
            "Intelligence",
            "SpellBuff",
            "LearnSpell"
          ]
        },
        {
          "name": "long_value",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "long_value2",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "string_value",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Spells",
      "table": "spells",
      "columns": [
        {
          "name": "spell_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "spell_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "spell_description",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_target",
          "kind": "Enum",
          "sql": "INT",
          "required": true,
          "pk": false,
          "enumNames": [
            "Target",
            "Self",
            "Group"
          ]
        },
        {
          "name": "class_restrictions",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_aether",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "100",
          "required": false,
          "pk": false
        },
        {
          "name": "spellbook_graphic",
          "kind": "Int",
          "sql": "INT",
          "required": true,
          "pk": false
        },
        {
          "name": "spellbook_graphic_file",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_static_cost",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_percent_cost",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_static_cost",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_percent_cost",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "sp_static_cost",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "sp_percent_cost",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_effect_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Spell Effects"
        }
      ],
      "composites": [
        {
          "kind": "Bitmask",
          "columns": [
            "class_restrictions"
          ],
          "source": "Classes"
        },
        {
          "kind": "Graphic",
          "columns": [
            "spellbook_graphic",
            "spellbook_graphic_file"
          ]
        }
      ],
      "indexes": []
    },
    {
      "sheet": "Spell Effects",
      "table": "spell_effects",
      "columns": [
        {
          "name": "spell_effect_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "spell_effect_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "spell_animation",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_animation_file",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_display",
          "kind": "Enum",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "Character",
            "Tile"
          ]
        },
        {
          "name": "target_type",
          "kind": "Enum",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "Target",
            "LineFront",
            "Cross",
            "Plus",
            "Random",
            "Area",
            "TriangleFront"
          ]
        },
        {
          "name": "target_size",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_effected",
          "kind": "Enum",
          "sql": "INT",
          "required": true,
          "pk": false,
          "enumNames": [
            "Self",
            "NPC",
            "SelfNPC",
            "Player",
            "SelfPlayer",
            "NPCPlayer",
            "SelfNPCPlayer"
          ]
        },
        {
          "name": "min_level_effected",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level_effected",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "effect_type",
          "kind": "Enum",
          "sql": "INT",
          "required": true,
          "pk": false,
          "enumNames": [
            "Formula",
            "Buff",
            "Permanent",
            "Tick",
            "TickBuff",
            "Teleport",
            "Bind",
            "Stun",
            "Root",
            "Snare",
            "Viral",
            "Invisible",
            "SeeInvisible",
            "OnAttack",
            "OnMeleeHit",
            "PetTame",
            "PetAttack",
            "PetDefend",
            "PetDestroy",
            "PetFollow",
            "PetNeutral",
            "Script"
          ]
        },
        {
          "name": "effect_duration",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "do_attack_animation",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "do_cast_animation",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_damage_effects",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_energy_type",
          "kind": "Enum",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "None",
            "Fire",
            "Water",
            "Spirit",
            "Air",
            "Earth"
          ]
        },
        {
          "name": "hp_change_formula",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_change_formula",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "sp_change_formula",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "hp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "sp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_ac",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_str",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_sta",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_dex",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_int",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_fire",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_water",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_spirit",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_air",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_earth",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "haste",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_damage",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_crit",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "melee_damage",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "melee_crit",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "damage_reduce",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "move_speed",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "oneffect_text",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "offeffect_text",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "face_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_id",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_r",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_g",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_b",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hair_a",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_r",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_g",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_b",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "body_a",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "teleport_map",
          "kind": "Id",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false,
          "ref": "Maps"
        },
        {
          "name": "teleport_x",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "teleport_y",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "taunt_aggro",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "works_in_pvp",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "works_not_in_pvp",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "buff_removable",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "buff_graphic",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "buff_graphic_file",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "buff_doesnt_stack_over",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "buff_stacks_over",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "random_join_chance",
          "kind": "Decimal",
          "sql": "DECIMAL(5,2)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "on_hit_spell_effect_id",
          "kind": "Id",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "ref": "Spell Effects"
        },
        {
          "name": "on_hit_spell_chance",
          "kind": "Decimal",
          "sql": "DECIMAL(5,2)",
          "default": "100",
          "required": false,
          "pk": false
        },
        {
          "name": "on_attack_spell_effect_id",
          "kind": "Id",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false,
          "ref": "Spell Effects"
        },
        {
          "name": "on_attack_spell_chance",
          "kind": "Decimal",
          "sql": "DECIMAL(5,2)",
          "default": "100",
          "required": false,
          "pk": false
        },
        {
          "name": "snare_percent",
          "kind": "Decimal",
          "sql": "DECIMAL(5,2)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "only_hits_one_npc",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [
        {
          "kind": "Graphic",
          "columns": [
            "spell_animation",
            "spell_animation_file"
          ]
        },
        {
          "kind": "Rgba",
          "columns": [
            "hair_r",
            "hair_g",
            "hair_b",
            "hair_a"
          ]
        },
        {
          "kind": "Rgba",
          "columns": [
            "body_r",
            "body_g",
            "body_b",
            "body_a"
          ]
        },
        {
          "kind": "Graphic",
          "columns": [
            "buff_graphic",
            "buff_graphic_file"
          ]
        }
      ],
      "indexes": []
    },
    {
      "sheet": "Warptiles",
      "table": "warptiles",
      "columns": [
        {
          "name": "map_id",
          "kind": "Id",
          "sql": "SMALLINT",
          "required": true,
          "pk": false,
          "ref": "Maps"
        },
        {
          "name": "map_x",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "map_y",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "warp_id",
          "kind": "Id",
          "sql": "SMALLINT",
          "required": true,
          "pk": false,
          "ref": "Maps"
        },
        {
          "name": "warp_x",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "warp_y",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Maps",
      "table": "maps",
      "columns": [
        {
          "name": "map_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "map_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "map_filename",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "pvp_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "chat_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "auction_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "shout_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "spells_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "bind_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00270\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "items_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "pets_enabled",
          "kind": "Bool",
          "sql": "CHAR(1)",
          "default": "\u00271\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Map Required Items",
      "table": "map_required_items",
      "columns": [
        {
          "name": "map_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Maps"
        },
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Items"
        }
      ],
      "composites": [],
      "indexes": [
        "map_id"
      ]
    },
    {
      "sheet": "Combinations",
      "table": "combinations",
      "columns": [
        {
          "name": "combination_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "combination_name",
          "kind": "Text",
          "sql": "VARCHAR(64)",
          "required": true,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "class_restrictions",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        }
      ],
      "composites": [
        {
          "kind": "Bitmask",
          "columns": [
            "class_restrictions"
          ],
          "source": "Classes"
        }
      ],
      "indexes": []
    },
    {
      "sheet": "Combination Item Required",
      "table": "combination_item_required",
      "columns": [
        {
          "name": "combination_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Combinations"
        },
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Items"
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Combination Item Result",
      "table": "combination_item_results",
      "columns": [
        {
          "name": "combination_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Combinations"
        },
        {
          "name": "item_template_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Items"
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Titles",
      "table": "item_titles",
      "columns": [
        {
          "name": "id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "item_usetype",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "NoUse",
            "OneTime",
            "Armor",
            "Weapon",
            "Scroll",
            "HairDye",
            "Letter",
            "Money",
            "Recipe"
          ]
        },
        {
          "name": "item_slot",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "20",
          "required": false,
          "pk": false,
          "enumNames": [
            "Helmet",
            "Shield",
            "OneHanded",
            "TwoHanded",
            "Ring",
            "Necklace",
            "Pauldrons",
            "Cloak",
            "Belt",
            "Gloves",
            "Chest",
            "Pants",
            "Shoes",
            "Mount",
            "Misc"
          ]
        },
        {
          "name": "chance",
          "kind": "Decimal",
          "sql": "DECIMAL(5,4)",
          "required": true,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Surnames",
      "table": "item_surnames",
      "columns": [
        {
          "name": "id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "min_level",
          "kind": "Int",
          "sql": "INT",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "max_level",
          "kind": "Int",
          "sql": "INT",
          "default": "50",
          "required": false,
          "pk": false
        },
        {
          "name": "min_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "max_experience",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "item_usetype",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false,
          "enumNames": [
            "NoUse",
            "OneTime",
            "Armor",
            "Weapon",
            "Scroll",
            "HairDye",
            "Letter",
            "Money",
            "Recipe"
          ]
        },
        {
          "name": "item_slot",
          "kind": "Enum",
          "sql": "SMALLINT",
          "default": "20",
          "required": false,
          "pk": false,
          "enumNames": [
            "Helmet",
            "Shield",
            "OneHanded",
            "TwoHanded",
            "Ring",
            "Necklace",
            "Pauldrons",
            "Cloak",
            "Belt",
            "Gloves",
            "Chest",
            "Pants",
            "Shoes",
            "Mount",
            "Misc"
          ]
        },
        {
          "name": "chance",
          "kind": "Decimal",
          "sql": "DECIMAL(5,4)",
          "required": true,
          "pk": false
        },
        {
          "name": "script_path",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        },
        {
          "name": "script_params",
          "kind": "Text",
          "sql": "TEXT",
          "default": "\u0027\u0027",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Classes",
      "table": "classes",
      "columns": [
        {
          "name": "class_id",
          "kind": "Id",
          "sql": "INTEGER",
          "required": true,
          "pk": true
        },
        {
          "name": "class_name",
          "kind": "Text",
          "sql": "TEXT",
          "required": true,
          "pk": false
        },
        {
          "name": "ac_multiplier",
          "kind": "Decimal",
          "sql": "DECIMAL(9,2)",
          "default": "1",
          "required": false,
          "pk": false
        },
        {
          "name": "vita_cost",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "200000",
          "required": false,
          "pk": false
        },
        {
          "name": "mana_cost",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "200000",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Class Info",
      "table": "class_info",
      "columns": [
        {
          "name": "class_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Classes"
        },
        {
          "name": "level",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "level_up_exp",
          "kind": "Int",
          "sql": "BIGINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "player_hp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "player_mp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "player_sp",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_ac",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_str",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_sta",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_dex",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "stat_int",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_fire",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_water",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_spirit",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_air",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "res_earth",
          "kind": "Int",
          "sql": "SMALLINT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "hp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_percent_regen",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "mp_static_regen",
          "kind": "Int",
          "sql": "INT",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "haste",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_damage",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "spell_crit",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "melee_damage",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "melee_crit",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        },
        {
          "name": "damage_reduce",
          "kind": "Decimal",
          "sql": "DECIMAL(9,4)",
          "default": "0",
          "required": false,
          "pk": false
        }
      ],
      "composites": [],
      "indexes": []
    },
    {
      "sheet": "Class Levelup Spells",
      "table": "classes_levelup_spells",
      "columns": [
        {
          "name": "class_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Classes"
        },
        {
          "name": "level",
          "kind": "Int",
          "sql": "SMALLINT",
          "required": true,
          "pk": false
        },
        {
          "name": "spell_id",
          "kind": "Id",
          "sql": "INT",
          "required": true,
          "pk": false,
          "ref": "Spells"
        }
      ],
      "composites": [],
      "indexes": []
    }
  ]
};
