using System.Text.Json;
using System.Text.Json.Serialization;

namespace Goose.Tools.SchemaGen;

/// <summary>Renders the schema model as a JS file assigning one global. The Apps Script editor
/// includes this verbatim; it is not fetched or parsed at runtime.</summary>
public static class SchemaJs
{
    private static readonly JsonSerializerOptions Options = new()
    {
        WriteIndented = true,
        // Environment.NewLine by default, so a Windows rebuild of the committed schema.js would
        // emit CRLF inside the JSON while the header and footer below stay \n — mixed endings, a
        // whole-file diff, and a failing up-to-date check on a file that is semantically current.
        NewLine = "\n",
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static string Render(SchemaRoot model)
    {
        var json = JsonSerializer.Serialize(model, Options);
        return "// Generated by tools/SchemaGen. Do not edit by hand.\n" +
               $"var GOOSE_SCHEMA = {json};\n";
    }
}
