//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvToSql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvToSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE IllutiaGoose;
        ///
        ///DROP TABLE item_templates;
        ///CREATE TABLE item_templates (
        ///  item_template_id INT NOT NULL,
        ///  item_usetype SMALLINT NOT NULL,
        ///  item_name VARCHAR(64) NOT NULL,
        ///  item_description VARCHAR(64) DEFAULT &apos;&apos; NOT NULL,
        ///  player_hp INT DEFAULT 0 NOT NULL,
        ///  player_mp INT DEFAULT 0 NOT NULL,
        ///  player_sp INT DEFAULT 0 NOT NULL,
        ///  stat_ac SMALLINT DEFAULT 0 NOT NULL,
        ///  stat_str SMALLINT DEFAULT 0 NOT NULL,
        ///  stat_sta SMALLINT DEFAULT 0 NOT NULL,
        ///  stat_dex SMALLINT DEFAULT 0 NOT NULL,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlTemplate {
            get {
                return ResourceManager.GetString("sqlTemplate", resourceCulture);
            }
        }
    }
}
