using System.Text.RegularExpressions;

namespace Tools.Tests;

/// <summary>Asserts on the BUILT bundles under tools/DataEditor — the actual input to the editor
/// front end — rather than on a freshly packed atlas held in memory.
///
/// SKIPS WHEN THEY ARE ABSENT, which is the normal state of a fresh checkout: the bundles embed
/// the client's art and are gitignored, so they exist only on a machine that has run
/// tools/SpriteBundle. They were committed once, and these were plain [Fact]s then, on the
/// reasoning that a file in the repo is a file every run can be held to. That reasoning went out
/// with the files. Skipping is not a weakening here — it is the same asset gate the builder tests
/// already use, moved one step downstream: no client tree, no bundle, nothing to assert.
///
/// What still runs, and where: on a machine that HAS built them, these catch a truncated write or
/// an empty regeneration before that bundle is deployed to a sidebar. In CI they skip, and the
/// build script is what stands between a missing bundle and a broken deploy — it exits non-zero
/// rather than warning (build.mjs step 3).
///
/// Content equality against a rebuild is deliberately NOT asserted: the bundles derive from a
/// separate client checkout at an unpinned revision, so such a test would fail on every machine
/// whose art had moved ahead — unfixable from this repo.</summary>
public class BundleArtifactTests
{
    public static TheoryData<string> BundleNames => ["icons", "parts", "effects"];

    [SkippableTheory]
    [MemberData(nameof(BundleNames))]
    public void Built_bundle_has_the_generated_header(string name)
    {
        var html = ReadBundle(name);

        Assert.StartsWith("<script>\n// Generated by tools/SpriteBundle", html);
        Assert.Contains($"GOOSE_SPRITES[\"{name}\"] = {{", html);
        Assert.EndsWith("</script>\n", html);
    }

    [SkippableTheory]
    [MemberData(nameof(BundleNames))]
    public void Built_bundle_carries_a_png_and_a_non_empty_rect_index(string name)
    {
        var html = ReadBundle(name);

        Assert.Contains("\"png\": \"data:image/png;base64,", html);

        var start = html.IndexOf("\"rects\": {", StringComparison.Ordinal);
        Assert.True(start >= 0, $"sprites-{name}.html has no \"rects\" object.");

        // An empty index would still parse and still assign the global; only its contents
        // distinguish a real bundle from one regenerated against an empty asset tree.
        var entries = Regex.Matches(html[start..], @"^\s+"".*"": \[\d+,\d+,\d+,\d+\],?$",
                                    RegexOptions.Multiline).Count;
        Assert.True(entries > 0, $"sprites-{name}.html has an empty rect index.");
    }

    /// <summary>Skips rather than fails when the bundle is not there. An absent bundle means
    /// "this checkout has not built one", which is not a defect for this repo to report — see the
    /// class summary. A bundle that EXISTS is still held to every assertion above.</summary>
    private static string ReadBundle(string name)
    {
        var path = Path.Combine(RepoRoot(), "tools", "DataEditor", $"sprites-{name}.html");
        Skip.IfNot(File.Exists(path),
            $"sprites-{name}.html has not been built in this checkout (it is gitignored). " +
            "Build it with: dotnet run --project tools/SpriteBundle -- " +
            "<client-assets-dir> tools/DataEditor");
        return File.ReadAllText(path);
    }

    /// <summary>The test binary sits at tools/Tools.Tests/bin/&lt;config&gt;/net10.0.</summary>
    private static string RepoRoot()
    {
        var root = Path.GetFullPath(
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        Assert.True(Directory.Exists(Path.Combine(root, "tools", "SpriteBundle")),
            $"Could not resolve the repo root from {AppContext.BaseDirectory} (got {root}).");
        return root;
    }
}
