using System.Text.RegularExpressions;

namespace Tools.Tests;

/// <summary>Asserts on the committed bundles under tools/DataEditor — the actual input to the
/// editor front end — rather than on a freshly built atlas.
///
/// Deliberately plain [Fact]s, not SkippableFact: everything here reads files in this repo and
/// needs no client checkout, so it runs for everyone and in CI. That is the whole point. The
/// builder tests are asset-gated and therefore assert nothing in a checkout-less environment,
/// which left the committed 4.4 MB covered by nothing at all.
///
/// Content equality against a rebuild is deliberately NOT asserted: the bundles derive from a
/// separate client checkout, so such a test would have to be asset-gated, making it green in CI
/// and red only on teammates' machines whenever the client's art moved ahead — failing exactly
/// where it is least actionable. These checks instead catch what a repo can be responsible for:
/// a truncated write, an empty regeneration, an accidental deletion.</summary>
public class BundleArtifactTests
{
    public static TheoryData<string> BundleNames => ["icons", "parts", "effects"];

    [Theory]
    [MemberData(nameof(BundleNames))]
    public void Committed_bundle_has_the_generated_header(string name)
    {
        var html = ReadBundle(name);

        Assert.StartsWith("<script>\n// Generated by tools/SpriteBundle", html);
        Assert.Contains($"GOOSE_SPRITES[\"{name}\"] = {{", html);
        Assert.EndsWith("</script>\n", html);
    }

    [Theory]
    [MemberData(nameof(BundleNames))]
    public void Committed_bundle_carries_a_png_and_a_non_empty_rect_index(string name)
    {
        var html = ReadBundle(name);

        Assert.Contains("\"png\": \"data:image/png;base64,", html);

        var start = html.IndexOf("\"rects\": {", StringComparison.Ordinal);
        Assert.True(start >= 0, $"sprites-{name}.html has no \"rects\" object.");

        // An empty index would still parse and still assign the global; only its contents
        // distinguish a real bundle from one regenerated against an empty asset tree.
        var entries = Regex.Matches(html[start..], @"^\s+"".*"": \[\d+,\d+,\d+,\d+\],?$",
                                    RegexOptions.Multiline).Count;
        Assert.True(entries > 0, $"sprites-{name}.html has an empty rect index.");
    }

    private static string ReadBundle(string name)
    {
        var path = Path.Combine(RepoRoot(), "tools", "DataEditor", $"sprites-{name}.html");
        Assert.True(File.Exists(path),
            $"Expected the generated bundle at {path}. Regenerate with: " +
            "dotnet run --project tools/SpriteBundle -- <client-assets-dir> tools/DataEditor");
        return File.ReadAllText(path);
    }

    /// <summary>The test binary sits at tools/Tools.Tests/bin/&lt;config&gt;/net10.0.</summary>
    private static string RepoRoot()
    {
        var root = Path.GetFullPath(
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        Assert.True(Directory.Exists(Path.Combine(root, "tools", "SpriteBundle")),
            $"Could not resolve the repo root from {AppContext.BaseDirectory} (got {root}).");
        return root;
    }
}
