using Goose.Tools.SchemaGen;

namespace Tools.Tests;

public class SchemaJsTests
{
    [Fact]
    public void Assigns_a_single_global()
    {
        var js = SchemaJs.Render(SchemaModel.Build());

        Assert.StartsWith("// Generated by tools/SchemaGen", js);
        Assert.Contains("var GOOSE_SCHEMA = {", js);
        Assert.EndsWith("};\n", js);
    }

    [Fact]
    public void Uses_lowercase_json_property_names()
    {
        var js = SchemaJs.Render(SchemaModel.Build());

        Assert.Contains("\"sheet\": \"Items\"", js);
        Assert.Contains("\"table\": \"item_templates\"", js);
        Assert.DoesNotContain("\"Sheet\":", js);
    }

    [Fact]
    public void Omits_null_optional_fields()
    {
        var js = SchemaJs.Render(SchemaModel.Build());

        // Non-enum, non-FK columns should not carry empty keys.
        Assert.DoesNotContain("\"enumNames\": null", js);
        Assert.DoesNotContain("\"ref\": null", js);
    }

    [Fact]
    public void Body_is_parseable_json()
    {
        var js = SchemaJs.Render(SchemaModel.Build());

        var start = js.IndexOf('{');
        var end = js.LastIndexOf('}');
        var json = js[start..(end + 1)];
        var doc = System.Text.Json.JsonDocument.Parse(json);

        Assert.Equal(21, doc.RootElement.GetProperty("sheets").GetArrayLength());
    }
}
